# Generated by Django 4.2.1 on 2023-06-08 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benie_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='cover',
            field=models.URLField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='poem',
            name='cover_source',
            field=models.URLField(blank=True, default='', max_length=5000, null=True),
        ),
    ]
