# Generated by Django 4.2.1 on 2023-05-21 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benie_app', '0002_chapter_contact_feedback_notification_password_poem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='cover_source',
            field=models.URLField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
