# Generated by Django 4.2.1 on 2023-05-21 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benie_app', '0003_alter_poem_cover_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='tagged',
            field=models.ManyToManyField(blank=True, null=True, to='benie_app.tag'),
        ),
    ]
